### ISSUE TITLE
Use Case #3: Save Player Data

### ISSUE THREAD

**Issue by razzacktiger** [angelochristian29/Basilisk-Zero#45]
Sprint Assigned: 
Assignee: 
Estimated Time: 
Due Date: 
Actual Time of Completion: 
Real time Completion: 
Timestamp: 3/31/2023 8:57:29
Use Case ID: 3
Use Case Name: Save Player Data
Use Case Category: User InformationActors:Players, System
Description: 
The player will be able to save the game at their current state using the save game feature.Normal Flow:
1. The player will open the menu
2. The player will hit the 'save game' button.
3. The player will then choose  which save slot they want to use for saving.
4. Their current progress in the game will be saved to their pc.
Alternate Flow:
noneRequirement Level: 
FR Essential
Priority:

Criticality: MMF

**Comment by angelochristian29** [comment]
This is hard to do in WebGL; therefore, we will try to make the narrative play out without the saving feature in mind. In other words, players will play the entire game in one sitting. This removes the need for saves unless on the WebGL platform. If the game transfers to an executable file then this feature may be added in later.
