### ISSUE TITLE
Use Case #8: In Game Puzzles

### ISSUE THREAD

**Issue by razzacktiger** [angelochristian29/Basilisk-Zero#48]
Sprint Assigned: 
Assignee: 
Estimated Time: 
Due Date: 
Actual Time of Completion: 
Real time Completion: 
Timestamp: 3/31/2023 9:58:35
Use Case ID: 8
Use Case Name: In Game Puzzles
Use Case Category: Gameplay MechanicsActors:Players, System
Description: 
Puzzles will be present in the environment that the player will have to interact with to progress.Normal Flow:
1. The player will find a puzzle tied to an object in the environment
2. The player will press E next to it
3. The player will solve the puzzle
4. The puzzle will no longer be interactive and the player can progress.
Alternate Flow:
noneRequirement Level: 
Desired
Priority:

Criticality: MMF

**Comment by angelochristian29** [comment]
If Saim has a working product by the beginning of next week then this feature will stay. Otherwise, this Use case is deprecated due to scope creep.
