### ISSUE TITLE
Use Case #1: Dialogue with NPC Charcters

### ISSUE THREAD

**Issue by razzacktiger** [angelochristian29/Basilisk-Zero#52]
Sprint Assigned: 
Assignee: 
Estimated Time: 
Due Date: 
Actual Time of Completion: 
Real time Completion: 
Timestamp: 3/26/2023 16:06:51
Use Case ID: 1
Use Case Name: Dialogue with NPC Charcters
Use Case Category: AI InteractionActors:Players, NPC Character, System
Description: 
Player can interact with NPC character and chooses dialogue based on NPC outputNormal Flow:
1. The player will approach an NPC character.
2. The player will press 'E' to interact.
3. Shortly after, the NPC will display a dialogue message.
4. The system will prompt the player a series of options to choos``e from in dialogue.
5. The player will choose a response and await NPC dialogue response.
Alternate Flow:
none Requirement Level: 
FR Essential
Priority:

Criticality: MMF

**Comment by angelochristian29** [comment]
Dialogue system is fully fleshed out and works when applied to new NPC characters.
