### ISSUE TITLE
Use Case #9: Menu screen

### ISSUE THREAD

**Issue by razzacktiger** [angelochristian29/Basilisk-Zero#53]
Sprint Assigned: 
Assignee: 
Estimated Time: 
Due Date: 
Actual Time of Completion: 
Real time Completion: 
Timestamp: 4/16/2023 14:34:47
Use Case ID: 9
Use Case Name: Menu screen
Use Case Category: User InterfaceActors:Players, System
Description: 
The players will be greeted with a menu screen that lets them start a new game, load game, change settings, or quit the game.Normal Flow:
1. The player will be prompted with the menu
2. The player can select from four options.
3. When the player clicks on an option, it should redirect them to what the options say
Alternate Flow:
NoneRequirement Level: 
FR Essential
Priority:

Criticality:

**Comment by angelochristian29** [comment]
The "Back" button on the Settings Main Menu page now works properly and loads the first floor.

**Comment by angelochristian29** [comment]
The in-game menu screen works when the player presses "ESC". The menu has an inventory menu that currently works and updates when the player picks up items.
